### ISSUE TITLE
[BUG]-LinkToApi method throws exception

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#218]
**Describe the bug**
When attempting to instantiate a JoinMapAdvanced and bridge to it I get an exception

**Stacktrace**
[16:14:25.389]App 2:[eiscBridge-Displays] Linking Devices...
[16:14:25.392]App 2:[eiscBridge-Displays] Linking Device: 'Display01'
[16:14:25.393]App 2:[eiscBridge-Displays] 'Display01' is IBridgeAdvanced
[16:14:25.413]App 2:[eiscBridge-Displays] ERROR: Device PostActivation failure:
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at PepperDash.Essentials.Core.JoinMapBaseAdvanced.AddJoins(Type type)
   at PepperDash.Essentials.Core.JoinMapBaseAdvanced..ctor(UInt32 joinStart, Type type)
   at PepperDash.Essentials.Core.Bridges.DisplayControllerJoinMap..ctor(UInt32 joinStart)
   at EpsonProjectorEpi.EpsonProjectorJoinMap..ctor(UInt32 joinStart)
   at EpsonProjectorEpi.EpsonProjector.LinkToApi(BasicTriList trilist, UInt32 joinStart, String joinMapKey, EiscApiAdvanced bridge)
   at PepperDash.Essentials.Bridges.EiscApi.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()

**To Reproduce**
Call LinkToApi and instantiate a joinMap that inherits JoinMapBaseAdvanced

**Comment by ngenovese11** [comment]
To add some context, the JoinMap is inheriting/extending DisplayControllerJoinMap... not sure if this makes a difference

**Comment by andrew-welker** [comment]
I see this is for the Epson Projector plugin. I'll take a look later this evening and see what's going on.

**Comment by ngenovese11** [comment]
I appreciate it


____________________________
Nick Genovese
Software Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

Email: ngenovese@pepperdash.com<mailto:ngenovese@pepperdash.com>
Direct: 617.206.9812
Toll free: 800.377.9112 x444
Fax: 617.208.0124

Introducing PepperDash Portal™<http://www.pepperdash.com/products/portal/>, the first and only AV Standards Management Platform.

**Comment by ndorin** [comment]
Seems like the obvious problem is that you’re still using the old ISedan interface.  With the weather finally picking up, maybe it’s time to finally splurge on the IConvertible? 😉

Come on, Nick… Loosen up that collar and put the top down.  Feel the wind in your hair for once!

Thanks,

Neil Dorin
Software Developer /SC
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>
Introducing PepperDash Portal™<http://www.pepperdash.com/products/portal/>, the first and only AV Standards Management Platform.

**Comment by andrew-welker** [comment]
@ngenovese11 all joking aside, which version of Essentials are you referencing in the Epson plugin? Looking at the join map, it appears to still be using the old style instead of the new style with JoinDataComplete properties. Because of that, there's not a direct conversion between the `EpsonProjectorJoinMap` type and the `JoinMapAdvanced` class, hence the exception. I'm away from my desk for a while, but I'll take another look later tonight.

**Comment by ngenovese11** [comment]
yeah I _just_ put up my changes to Github; so this is with the new joinMap and essentials 1.5.4

**Comment by andrew-welker** [comment]
Also, be aware that there are 2 different versions of the built-in display join map. One in `PepperDash.Essentials` that is the old-style IBridge, and another in `PepperDash.Essentials.Core` that is IBridgeAdvanced

**Comment by ngenovese11** [comment]
yep I just double checked I am using PepperDash.Essentials.Core

![image](https://user-images.githubusercontent.com/23391587/83071737-99149900-a03b-11ea-9d38-0d5ad99fbfd8.png)

**Comment by ngenovese11** [comment]
check out my development branch when you're back at your desk

**Comment by andrew-welker** [comment]
Lol... checking it all out on my phone. I think the problem is that the AddJoins method is attempting to convert to `DisplayControllerJoinMap` instead of `EpsonProjectorJoinMap` and failing. The `JoinMapAdvanced` class has a constructor that takes a type parameter, but it's not exposed on the `DisplayControllerJoinMap`, so you can't call it from the join map class in the plugin.

There are a couple of options for now: don't derive from DisplayControllerJoinMap and implement everything in your join map, and (probably much simpler)  instantiate an instance of DisplayControllerJoinMap in the LinkToApi method and add the joins to the Joins dictionary yourself prior to calling the bridge.AddJoinMap method.

In the meantime, I'll also look at implementing a second constructor on the internal bridges that takes the Type parameter and passes it through to where it should be

**Comment by ngenovese11** [comment]
Understood; for now I’ll just write my own JoinMap until if/when a fix gets put on the roadmap.

Thanks!

____________________________
Nick Genovese
Software Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

Email: ngenovese@pepperdash.com<mailto:ngenovese@pepperdash.com>
Direct: 617.206.9812
Toll free: 800.377.9112 x444
Fax: 617.208.0124

Introducing PepperDash Portal™<http://www.pepperdash.com/products/portal/>, the first and only AV Standards Management Platform.
