### ISSUE TITLE
[BUG]-ReleaseAndMakeRoute throws error if Destination is also IRouting

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#219]
**Describe the bug**
I was doing some testing of IRouting with the NVX plugin.  I was calling ReleaseAndMakeRoute() on a receiver (IRoutingInputs).  Since this device is the first in the chain, it gets added to the route table with a Null RoutingOutputPort; however, when the ExecuteRoutes method is called, since the device is IRouting it attempts to call a route with a null Output port.

**To Reproduce**
1.  Attempt to call ReleaseAndMakeRoute() from an IRouting device

**Additional Context**
I have made a fix to only add the Sink device to the RouteDescriptor list _if_ it is also an IRoutingSinkWithSwitching

**Comment by andrew-welker** [comment]
Are you treating NVX devices as a sink? Most of the time, they should be treated as a midpoint. The display is the sink.

**Comment by ngenovese11** [comment]
ReleaseAndMakeRoute only requires the destination device to be IRoutingInputs; not necessarily a routing sink.

**Comment by andrew-welker** [comment]
After discussion with @ngenovese11, @ndorin, @andrew-welker, and @hvolmer, we determined that the real issue is the `ReleaseAndMakeRoute` method should only be called on sinks, not anything that implements `IRoutingInputs`. The fix here is to change `ReleaseAndMakeRoute` to be an extension on `IRoutingSinkNoSwitching` instead of on `IRoutingInputs`. That will ensure that the issue that @ngenovese11 encountered doesn't happen by restricting the calling of `ReleaseAndMakeRoutes` to only be on sinks.
