### ISSUE TITLE
[FEATURE]-Methodolgy for Cresnet Devices to connect to IDeviceBranch

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#292]
**Is your feature request related to a problem? Please describe.**
Currently, there is no mechanism by which a cresnet device can connect to any device other than a control system.  DIN-CENCN-2 and DIN-CENCN-2-POE Devices can also facilitate cresnet connections.

**Describe the solution you'd like**
Configuration files for Cresnet Devices should allow for devices other than the base processor to register to.  This mechanism should include both the key of the device, and the "branch" on the device to which it connects.

**Describe alternatives you've considered**
There is no viable solution.

**Additional context**
There is an impending client request for support of DIN-CENCN-2-xxx devices.  This is the first step in facilitating that.

**Comment by andrew-welker** [comment]
Looks like there are a couple of changes that need to happen

1. Cresnet devices need to start looking for the usage of the `ControlPortDevKey` in the Control config section. If it is not null or empty or doesn't equal `processor`, then the device is being run off of a DIN-CEN-CN
2. When the `ControlPortDevKey` is present, the `ControlPortNumber` will determine what branch on the DIN-CEN-CN should be used. There should be checks for if the value is greater than the number of branches present on the host device

All of this probably needs to take place in a PreActivation action, to ensure that the host device is constructed prior to the Cresnet device being created, and so that any possible other devices, like com ports, relays, or IO's can be registered in a PostActivation action.
