### ISSUE TITLE
[BUG]- Remotes not running preactivation func with internal gateway in latest 1.5.7 RC

### ISSUE THREAD

**Issue by jonavila** [PepperDash/Essentials#320]
**Describe the bug**
The remotes are not running the preactivation function when using an internal gateway. It seems the issue was introduced with this change:
https://github.com/PepperDash/Essentials/blob/release/1.5.7/essentials-framework/Essentials%20Core/PepperDashEssentialsBase/Remotes/Hrxx0WirelessRemoteController.cs#L68

When the gateway is internal, _gateway will always be null

**Expected behavior**
It should be possible to use an internal gateway to create and register a remote

**Comment by TrevorPayne** [comment]
Sorry about that - I completely refactored how child devices register to parent devices in the context of Cresnet and InfinetEx because of the addition of the Cresnet Gateway - I once again missed this case because I don't have equipment to test this specific scenario against.  Thanks for the bug report.  I've commited a prosepctive fix."

**Comment by TrevorPayne** [comment]
Take a look at [Hotfix-496](https://github.com/PepperDash/Essentials/releases/tag/1.5.7-hotfix-496)

**Comment by jonavila** [comment]
Thanks. That’ll do it.
