### ISSUE TITLE
[BUG]-Breaking change from 1.5.6 to 1.5.8 when referencing existing joinMap in Plugin

### ISSUE THREAD

**Issue by jkdevito** [PepperDash/Essentials#331]
**Describe the bug**
Updating Essentials from 1.5.6 to 1.5.8 - When referencing an existing joinMap the plugin BridgeJoinMap constructor previously only required joinStart, in 1.5.8 it is requiring joinStart and typeof.  This is a breaking change to plugins prior to 1.5.8.  Reviewed with @jtalborough.

**Expected behavior**
// as of 1.5.6
EvertzQuartzBaseJoinMap = new DmChassisControllerJoinMap(joinStart);

// as of 1.5.8 - breaking change of plugins referencing existing joinMaps
EvertzQuartzBaseJoinMap = new DmChassisControllerJoinMap(joinStart, typeof(DmChassisControllerJoinMap));

**Comment by andrew-welker** [comment]
This was due to the first attempt to fix issue #323 . The fix here is to make the single parameter constructor public again instead of internal, as the internal join maps are sometimes constructed directly in plugins, without creating a separate join map in the plugin. I'll also add some XML comments to make it clear what the intended use of each constructor is.

**Comment by andrew-welker** [comment]
As I was working on it, I realized that I could make the constructor to use for extending a join map protected, so it can only be used when the join map is being extended.
