### ISSUE TITLE
[BUG]-GlsOccupancySensorBase (Type: glsOdtCcn) or one of it's variants has a null CommunicationMonitor object

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#337]
**Describe the bug**
CommunicationMonitor object is null on instances of type glsOdcCcn which throws a null reference exception in the Fusion base SetUpError() method that set's up the Fusion error monitorin.

**Comment by andrew-welker** [comment]
I'm pretty sure this is happening because of the changes made to device activation for the occupancy sensors. The Communication Monitor for those devices isn't created until the PreActivation phase, but the `SetUpError` method is currently called when the Fusion device is constructed. We can move those construction actions in the Fusion setup to a PostActivation step, which should prevent the error from happening.

**Comment by TrevorPayne** [comment]
> I'm pretty sure this is happening because of the changes made to device activation for the occupancy sensors. The Communication Monitor for those devices isn't created until the PreActivation phase, but the `SetUpError` method is currently called when the Fusion device is constructed. We can move those construction actions in the Fusion setup to a PostActivation step, which should prevent the error from happening.

I was coming in here to post the same thing - I didn't think about that part of it when I made the changes to activation, but it makes perfect sense.  It probably affects any cresnet devices.

I think this probably would have been a problem regardless because if the fusion device is created for some reason before the cresnet device (or really any other device it's supposed to monitor) you're probably going to have this same issue.

**Comment by andrew-welker** [comment]
I have already inadvertently solved this in another branch when I was working on my DualDisplay stuff. There is a collection of methods that got moved to be a PostActivation action for just this reason. It also affects any classes that inherit from the Fusion Base class, as many of the methods are virtual, and the correct methods may not be called when the construction of the object happens.
