### ISSUE TITLE
Need additional detail about creating valid configuration files for standalone use

### ISSUE THREAD

**Issue by thurstylark** [PepperDash/Essentials#43]
For reference: I'm looking at this from a completely outside perspective, with the intention of learning how to put Essentials in place without the need to use the Portal to create config files. Here are a few questions that came up, which should help point out the additional detail needed:

- What objects are required to create a valid config file?
  - Or: What is the bare minimum necessary to create a valid (but not necessarily useful) config? 
  - Ideally, this should also extend down the tree of objects, specifying where the list of valid options is derived from where possible
  - This is mostly a request to add details on conceptualizing the different sections of the config, and how they're used to do useful things in the system
    - i.e.: "At the top level, the config requires a system object, a template object, a system_url string, and a template_url string. system_url and template_url are optional, and can be left blank, but must exist to create a valid config. Devices are added to a system by defining somethingsomething in the template object. This device template is then used in the system object in blablah ways..."
- How are devices added to a system? What is required to make Essentials aware of a device, and make them usable?
  - Based on the context in the example configurations, It seems like a device needs to be added to the template, and then can be used in the system (maybe more than once?), but this is not clear based on the documentation.
- How is logic defined? 
  - I'm assuming the easiest answer to this is "Bridge to an EISC and do logic in SIMPL Windows", but what defines the logic for systems where someone would not want to depend on SIMPL at all? 
  - Based on context, I believe that one would need to create a new room type, and then use it from the config, but it's not clear from the documentation that this is the case

I believe most of these questions are related to conceptualizing how Essentials handles different parts of its systems, but as it is, there's not a lot of conceptual information in the wiki from a usage perspective.

**Comment by ndorin** [comment]
Thanks for bearing with us while we flush out the documentation.  Comments like these are exactly what we need to help identify the gaps and how to fill them in.  More info will be forthcoming in the form of additional configuration snippets for each device type, 

In the meantime I can attempt to answer a couple of your questions here:

### Valid Config Structure

We'll obviously need to get into more detail in the future regarding the template/system model but at a high level this allows you to define two config objects that share the same structure.  The `template` is considered the parent object and gets merged with the `system` object when the file is loaded.  This mainly benefits scenarios where you have multiple instances of rooms with the same functionality.  The non system specify configuration information goes in the `template` and only the system specific into goes in the `system`.  This often means just the IP addresses of the devices for each unique system.  Values defined in `system` will override values also defined in `template`. This allows there to be default values in `template` without the need to remove them if they need to change for a particular system.

See below for more detail and a link to the new wiki page that focuses on configuration structure.

### Adding Devices to a System [Device and Device Manager Wiki Article](https://github.com/PepperDash/Essentials/wiki/Arch-1#device-and-devicemanager)

To add devices to a system they need to be defined as elements in the `devices` array in either `template` or `system` (or both).

We've added a [new page](https://github.com/PepperDash/Essentials/wiki/ConfigurationStructure) to the Wiki that goes into additional detail about configuration structure and how merging works between the `template` and `system` config objects. 

Hopefully this fills in some of the blanks and answers your questions.  Please let us know if you have follow up questions.

### How is logic defined

This really depends on what type of logic you're wanting to define.  The general idea is for most development to take place in the Plugin environment.  From there, it would start most often by extending one of the existing base classes. Almost everything inherits from PepperDash.Core.Device for two man reasons.  It can be added to DeviceManager and interacted with via console commands for Debugging and also because devices that register with DeviceManager use it's features to link up to each other and interact at runtime.

Without more specific detail in this question (feel free to add more) the best I can suggest is to have a look through the classes and find something that represents something you might want to define for yourself and look at it's class inheritance and any interfaces it implements.  From there if you have specific questions, don't hesitate to ask.

HTH

-Neil
