### ISSUE TITLE
[FEATURE]-Processor Device Creation debug condition is improper

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#453]
**Is your feature request related to a problem? Please describe.**
When creating a processor device in essentials, unless you define the type with hyphens as defined in the processor prompt, you get an error saying that the defined type and actual type are different.  You must define the type with hyphens, which seems to be in opposition to standard type names elsewhere in essentials - additionally this should probably be a case-insensitave ordinal string comparison here, and get rid of the ToLower()

**Describe the solution you'd like**
The string comparator in ControlSystem that triggers this error should remove the prompt hyphens and run the comparison again before the debug message is triggered.
Currently:
```csharp
if (devConf.Type.ToLower() != Global.ControlSystem.ControllerPrompt.ToLower())
    Debug.Console(0,
        "WARNING: Config file defines processor type as '{0}' but actual processor is '{1}'!  Some ports may not be available",
        devConf.Type.ToUpper(), Global.ControlSystem.ControllerPrompt.ToUpper());
```

Proposed:
```csharp
if (!String.Equals(devConf.Type, Global.ControlSystem.ControllerPrompt, StringComparison.OrdinalIgnoreCase) ||
                            !String.Equals(devConf.Type, Global.ControlSystem.ControllerPrompt.Replace("-",""), 
                            StringComparison.OrdinalIgnoreCase))
                            Debug.Console(0,
                                "WARNING: Config file defines processor type as '{0}' but actual processor is '{1}'!  Some ports may not be available", 
                                 devConf.Type.ToUpper(), Global.ControlSystem.ControllerPrompt.ToUpper());
```

**Describe alternatives you've considered**
The debug statement can be easily ignored, but since the mechanism for determining the debug condition may not be easily apparent, it's probably better to correctly ascertain the context.

**Additional context**
This was discovered during the creation of a DMPS configuration file.

**Comment by ndorin** [comment]
Interesting condition here.  Because we're comparing to the controller prompt property value returned by the ControlSystem class, we're somewhat at the whim of how Crestron defines the prompts.  I'm inclined to agree that removing any hyphen characters and doing a same/ignored case comparison achieves more consistency with Crestron's class name scheme and also our own typename scheme.

Realistically, though, this isn't an "error" and is accurately reported in the debug statement as a "WARNING" simply for the purposes of notifying that the inconsistency was noticed.  That said, we shouldn't be warning of an inconsistency if it doesn't in fact exist.  Good catch, @TrevorPayne.
