### ISSUE TITLE
[FEATURE]-StatusSign Improvements

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#732]
**Is your feature request related to a problem? Please describe.**
StatusSign outputs 0-65535 instead of 0-100 as feedback for light brightness levels

**Describe the solution you'd like**
Utilize `SimplSharpDeviceHelper.UshortToPercent` to output 0-100 for brightness feedback 

**Describe alternatives you've considered**
Utilize inconsistent numbering schemes

**Additional context**
Unable to get color mixing currently - still testing.

**Comment by andrew-welker** [comment]
So after some investigation, the Enum that is used for setting the brightness levels expects 19661 for 30% (.3 * 65535 => 19660.5). Because of the Math.Round's function default `ToEven` midpoint rounding strategy, the recommended helper method's output is 19660 instead of 19661, so 30% for ANY of the 3 LED's doesn't work.

Also, any attempt to mix red & green LED's from S#Pro appears to not work. @TrevorPayne is going to open a case for that.
