### ISSUE TITLE
[FEATURE]-Add new Cisco codec features

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#865]
**Is your feature request related to a problem? Please describe.**
The following features are needed to achieve feature parity with some SIMPL Cisco modules:

1.	Trigger to hang up individual callers 1-8.
2.	Feedback reflecting amount of currently connected calls. This value does not seem to match the 'Current Participant count' analog object as getting into a call does not increment the value for this object.
3.	Feedback reflecting call duration for caller 1-8. Looking for serial string with call timer per call.
4.	Trigger and feedback selecting DTMF control for caller 1-8 to determine which call the DTMF keypad controls.
5.	Trigger/feedback to control far end camera pan, tilt, zoom in/out, focus near/far, or preset recall.
6.	Triggers to control near end camera focus near/far.
7.	Trigger/feedback for ringtone volume set/fb and mute (low priority item, but it is used on one project).
8.	Trigger/feedback choosing near end presentation input 1-5 (stop already exists, but need a way to discretely choose input to start presentation on as client projects switch between various HDMI inputs for presentation).
9.	Trigger/feedback choosing near end source input 1-5 (typically triggered at the same time a local camera is selected when multiple local cameras are available for selection).
10.	Mechanism to select and dial entry from call history list (recently dialed entries), clear selected item, feedback for call history selected entry name and number, as well as list results of last 10 entries in the history list.
11.	Mechanism to select and dial 'multiple dial methods' from phonebook entry. Corporate directory has option to dial entries from either SIP, email address, or other (not a high priority item, but was recent feature request on last project).
12.	Essentials directory seems to dial a directory entry immediately when the analog value for selected entry-in has been propagated. Should the directory show caller info when I choose the directory entry but wait to dial until I press the digital trigger to dial selected directory entry?
13.	Trigger/feedback to hold caller 1-8.
14.	Trigger to resume caller 1-8 from hold.
15.	Trigger to join or merge with caller 1-8 as well as merge all.

**Comment by jonnyarndt** [comment]
Essentials v1.9.8-alpha-1681 throws a null reference exception when attempting to create the following device types: 'ciscoSparkPlusCodec', 'ciscoRoomKit, 'ciscospark', 'ciscowebexpro', or 'ciscowebex'.  Null ref exception is below.

[20:54:42.202]App 1:   at PepperDash.Essentials.Devices.Common.VideoCodec.Cisco.CiscoSparkCodec.SetFeedbackActions()
   at PepperDash.Essentials.Devices.Common.VideoCodec.Cisco.CiscoSparkCodec..ctor(DeviceConfig config, IBasicCommunication comm)
   at PepperDash.Essentials.Devices.Common.VideoCodec.Cisco.CiscoSparkCodecFactory.BuildDevice(DeviceConfig dc)
   at PepperDash.Essentials.Core.DeviceFactory.GetDevice(DeviceConfig dc)
   at PepperDash.Essentials.ControlSystem.LoadDevices()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()

**Comment by jonnyarndt** [comment]
I've reviewed the latest Cisco codec feature updates to the bridge and had some RFIs. Please review and let me know your thoughts.

1. What do the 'speed dial' digital signals on bridge accomplish at join To-SIMPL at 41-44? Do they simply recall a saved speed dial entry saved within the endpoint?
2. What is the purpose of the 'Dial Phone' object on bridge at join To-From-SIMPL at 71?
3. Why are there three separate instance of 'End a specific call by call index' on the bridge at join 81, 90, and 91 (all with a join-span of 8)?
4. How is it possible to save a Camera preset without first recalling it? Seems like I first have to recall the preset by updating analog value at bridge join 121. Would it be possible to have a separate analog input for save versus recall?
5. Does the camera mode auto/manual/off work for the last camera selected or discretely for the 'speaker-track' camera should one be installed? Example of speaker-track-on SIMPL application API call, 'xCommand Cameras SpeakerTrack Activate\n'.
6. Does 'Join first/second/third meeting' at bridge join 160-162 join merge with caller 1-3 or is this a meeting only function that has nothing to do with peer-to-peer calls?
7. What is the purpose of the digital bridge 'Removes the selected recent call item' item at join 181?
8. Is it possible that the bridge is sending the same feedback object for both bridge join 205 and 206 ('Presentation Local Only Feedback')?
9. What is the purpose of the 'advance selfview position' bridge join 211? What does that feature do?
10. Something is amiss with the 'Holds Call at specified index' and 'Activates Do Not Disturb Mode.  FB High if active.' both From-SIMPL at join 221? They can't both utilize SIMPL bridge join 221 and be From-SIMPL, correct? This seems to impact the remaining joins at 321 as the 'Holds Call at specified index' has a join span of 8.
11. Would it be possible to provide feedback for call hold state? I don't expect feedback for call resume, but feedback for call hold would be beneficial to show on touch panel. Join map text for call hold shows From-SIMPL only.
12. What does bridge join 223, 'Toggles Do Not Disturb Mode' To-SIMPL do? The wording is confusing. Is 222 a DND-On discrete while 223 is a DND-Off discrete? Does 223 join not provide feedback while 222 does?
13. Does the bridge include any serial feedback reflecting call duration for current calls? I see the recent call times, but no current call timer. No need to keep it accurate to the second, but perhaps every 3 seconds? Is this information already included in the 'Current call data XSIG'? If not, could it be?
14. Bridge does not include trigger/feedback to set the main video source for video input 1-5. Example existing API call for video 1 source, 'xCommand Video Input SetMainVideoSource SourceId: 1\n'
15. What is the XSIG layout for the 'Current call data' bridge serial join 2? Meaning, which output is for name versus number? Are there digital outputs for connected/connecting feedback or just serial?
16. How do I discretely select or dial from the provided list of contact methods? Would it be possible to include digital feedback To-SIMPL if/when multiple contact methods are possible to drive touch panel pop-up logic?
17. Would it be possible to add a 'JoinAllCalls' and a 'HoldAllCalls' From-SIMPL method?
18. Would it be possible to make the 'Current Layout Fb' serial join on the bridge a To-From-SIMPL rather than just a To-SIMPL mechanism?
19. Does the analog value to select the recent dial automatically dial the recent caller? Would it be possible to prevent auto-dialing the selected recent caller matching the phonebook directory list recent addition?
20. Would it be possible to poll the Cisco endpoint for its IP address and SIP URI info?
21. Would it be possible to include a From-SIMPL serial join on the bridge allowing the SIMPL application to send a serial command without having to create a unique TCP/IP or SSH connection to the endpoint? Some of the SIMPL application serial strings sent do not require feedback or are basing from fake feedback on last command sent. This would be very helpful.

**Comment by ndorin** [comment]
> I've reviewed the latest Cisco codec feature updates to the bridge and had some RFIs. Please review and let me know your thoughts.
> 
> 1. What do the 'speed dial' digital signals on bridge accomplish at join To-SIMPL at 41-44? Do they simply recall a saved speed dial entry saved within the endpoint?
* There are speed dial entries that can be specified in the device config (for example a webex bridge number).  These joins will dial those entries
> 2. What is the purpose of the 'Dial Phone' object on bridge at join To-From-SIMPL at 71?
* Pulsing this digital join will trigger the codec to dial the address specified by the `CurrentDialString` (Serial join 1).  Join description will be updated to clarify.
> 3. Why are there three separate instance of 'End a specific call by call index' on the bridge at join 81, 90, and 91 (all with a join-span of 8)?
* Descriptions fields were incorrect on join map definition. They will be updated to correctly describe the join functions.
> 4. How is it possible to save a Camera preset without first recalling it? Seems like I first have to recall the preset by updating analog value at bridge join 121. Would it be possible to have a separate analog input for save versus recall?
* Camera preset must be selected first, then the camera moved to the desired position and the `CameraPresetSelect` join pulsed to save the new position to that preset number.  This is fairly common functionality on codec modules and changing would break the existing API for existing systems.
> 5. Does the camera mode auto/manual/off work for the last camera selected or discretely for the 'speaker-track' camera should one be installed? Example of speaker-track-on SIMPL application API call, 'xCommand Cameras SpeakerTrack Activate\n'.
* These controls are not for any specific camera, but for the codec itself.  The `CameraModeAuto` (Activates SpeakerTrack), `CameraModeManual` (Deactivates SpeakerTrack) and `CameraModeOff` (performs video mute).  They effectively operate as interlocked modes and provide feedback to SIMPL as to the current mode.  Manual is always supported but auto and off modes depend on whether or not the hardware device supports those modes.
> 6. Does 'Join first/second/third meeting' at bridge join 160-162 join merge with caller 1-3 or is this a meeting only function that has nothing to do with peer-to-peer calls?
* These joins are not for joining/merging calls.  These are for joining scheduled meetings.
> 7. What is the purpose of the digital bridge 'Removes the selected recent call item' item at join 181?
* As requested in original issue item 10, this clears the selected item from the call history list, specified by the `SelectRecentCallItem` analog join.
> 8. Is it possible that the bridge is sending the same feedback object for both bridge join 205 and 206 ('Presentation Local Only Feedback')?
* Description on both joins was the same. Updated the description to differentiate, but the function of the joins should report accurately based on feedback from the device about the current presentation instances.  However, because the codec supports multiple presentation instances, these values may not necessarily be mutually exclusive.  We may need to play with the hardware to see how it reports under normal use cases and adjust how we determine the feedback accordingly.
> 9. What is the purpose of the 'advance selfview position' bridge join 211? What does that feature do?
* Toggles the position of the selfview window. Description has been update to be clearer.
> 10. Something is amiss with the 'Holds Call at specified index' and 'Activates Do Not Disturb Mode.  FB High if active.' both From-SIMPL at join 221? They can't both utilize SIMPL bridge join 221 and be From-SIMPL, correct? This seems to impact the remaining joins at 321 as the 'Holds Call at specified index' has a join span of 8.
* This was a mistake.  There was an overlap of joins specific to the cisco codec in the 221-229 range.  The cisco specific joins have been moved to the 241-249 range to resolve the conflict.
> 11. Would it be possible to provide feedback for call hold state? I don't expect feedback for call resume, but feedback for call hold would be beneficial to show on touch panel. Join map text for call hold shows From-SIMPL only.
* Feedback for call hold state is provided, but not on the same set of joins.  It's provided on the call status XSIG as a digital FB join. The first digital join on the XSIG reports if the call is active, the second digital join reports if the call is on hold.
> 12. What does bridge join 223, 'Toggles Do Not Disturb Mode' To-SIMPL do? The wording is confusing. Is 222 a DND-On discrete while 223 is a DND-Off discrete? Does 223 join not provide feedback while 222 does?
* There are three joins: `ActivateDoNotDisturbMode`, `DeactivateDoNotDisturbMode` and `ToggleDoNotDisturbMode`.  They have been moved up 20 joins to the 241-243 range to avoid the previously noted conflict.  Function should be self explainatory.
> 13. Does the bridge include any serial feedback reflecting call duration for current calls? I see the recent call times, but no current call timer. No need to keep it accurate to the second, but perhaps every 3 seconds? Is this information already included in the 'Current call data XSIG'? If not, could it be?
* This was added to the current call stats XSIG as the next serial join after the call status join for each call instance.
> 14. Bridge does not include trigger/feedback to set the main video source for video input 1-5. Example existing API call for video 1 source, 'xCommand Video Input SetMainVideoSource SourceId: 1\n'
* As per the original issue item 9 The `CameraNumberSelect` analog join value will now cause this command to be sent to the codec to select the camera input as this functionality was previously missing for the camera select function on the Cisco codec class.  Does this need to be exposed outside of the desire to switch cameras as a separate analog join?
> 15. What is the XSIG layout for the 'Current call data' bridge serial join 2? Meaning, which output is for name versus number? Are there digital outputs for connected/connecting feedback or just serial?
* This is difficult to document in the code itself and we don't have a current mechanism to report it via console command but here's the updated join pattern for the call status XSIG:

Digital FB 1: Call is Active (Connected)
Digital FB 2: Call is On Hold

Serial FB 1: Call Name
Serial FB 2: Call Number
Serial FB 3: Call Direction
Serial FB 4: Call Type
Serial FB 5: Call Status
Serial FB 6: Call Duration 

> 16. How do I discretely select or dial from the provided list of contact methods? Would it be possible to include digital feedback To-SIMPL if/when multiple contact methods are possible to drive touch panel pop-up logic?
* Good catch.  An XSIG was added to report the available contact methods for the selected contact, but no feedback as to whether the selected contact has none (folder), one or multiple contact methods.  I've added some new joins to address this:

`SelectedContactMethodCount` analog (102) reports the number of contact methods for the selected contact

In terms of dialing a contact method, the string reporting the number from the contact methods XSIG can be passed to the `CurrentDialString` input and the `ManualDial` digital can be pulsed to dial that method.  This is how it's accomplished in Essentials standalone applications.

Here's the join pattern for the contact methods XSIG:

Serial FB 1: Number
Serial FB 2: Contact Method ID
Serial FB 3: Device

> 17. Would it be possible to add a 'JoinAllCalls' and a 'HoldAllCalls' From-SIMPL method?
*  `JoinAllCalls` already exists at digital join 90.  Hold all calls was not requested in original issue.  It could be added if necessary.
> 18. Would it be possible to make the 'Current Layout Fb' serial join on the bridge a To-From-SIMPL rather than just a To-SIMPL mechanism?
* Currently we only support toggling the layout and providing feedback as to the current layout for Cisco devices.  We could add the ability to set a discrete layout by name from this serial join.  I don't think there's a way to determine what layouts are valid so the layout may or may not actually change based on the codec state and requested layout.
> 19. Does the analog value to select the recent dial automatically dial the recent caller? Would it be possible to prevent auto-dialing the selected recent caller matching the phonebook directory list recent addition?
> 20. Would it be possible to poll the Cisco endpoint for its IP address and SIP URI info?
* I've added a series of joins in the 301-305 range, both digital and analog that report various information about the codec, including it's IP address and SIP URI that was already available on the class but not exposed on the bridge.
> 21. Would it be possible to include a From-SIMPL serial join on the bridge allowing the SIMPL application to send a serial command without having to create a unique TCP/IP or SSH connection to the endpoint? Some of the SIMPL application serial strings sent do not require feedback or are basing from fake feedback on last command sent. This would be very helpful.
* Yes, we could add a serial join that would send the string directly to the codec via whatever connection method is being used (RS232, TCP, SSH).  I've added this already on serial join 5 `CommandToDevice` because it's a quick add with no potential breaking changes

**Comment by jonnyarndt** [comment]
#Problems/Questions - Items Tested - 2022-01-04# 

Are the items below something the products and services team could work together to review and resolve in tandem?

1. Ringtone volume set and feedback not working (I'm getting feedback from can't set the volume 0-100d to make any changes)
2. Standby state on and off as well as feedback is not working correctly (I'm reviewing screenshots from the Touch-10 and webpage provisioning, it's not working)
3. Phonebook directory is not populating on the touch panel, pressing 'Up one level' while on the top does not repropagate the list.
4. Serial text feedback not populating (IPv4-Address, SIP Phone Number, E.164 Alias, H323.ID, SIP URI)

**Comment by jonnyarndt** [comment]
**##Problems Ongoing**
[ ] CallXX.Hold.Btn and Fb is not working.
[ ] Pressing half-wake does not reflect feedback from codec that it's in half-wake. Requesting half-wake doesn't seem to force device to half-wake. Feedback of half-wake is not reported
[ ] When attempting to hang up call 1, there is an index out of range exception at: 'VideoCodec.VideoCodecBase+<>c__DisplayClass48.<LinkVideoCodecCallControlsToApi>b__3a ()'. I can still trigger the hangUpAllCalls, but I am not able to individually hang up call-1 without receiving the exception.
[ ] 'Incoming Call Name' on joinMap ID 51 and 'Incoming Call Number' on joinMap ID 52 are not populating during an incoming call.
[ ] When restarting Essentials while codec in a call, getting a JSON deserialization exception due to unexpected character. It happens often, but seems to change at what position the character is received at.
[ ] Serial text feedback for "IPv4-Address" not populating

**Items Tested & Confirmed Working**
[X] Phonebook directory feedback of names
[X] Recent call list feedback of names
[X] Self-View Toggle
[X] Ringtone volume Fb
[X] SIP Phone.Fb and SIP.URI.Fb
[X] Standby state trigger and feedback
[X] DND on/off and feedback state
[X] Camera names propagate
[X] Interesting! Selecting a camera seems to select 'Main' inputs on the VC codec
[X] HangUpAllCalls 
[X] Recent call select and pressing 'Connect' from Recent Calls
[X] Device Online feedback state
[X] Speaker-Track auto, manual, and off select and feedback
[X] Volume up/down/mute/mute toggle, and manual set as well as feedback
[X] Mic mute on/off/toggle and feedback
[X] Toggle self-view and feedback
[X] Feedback of number of connected calls
[X] Feedback of the number of reported cameras (is this really cameras or is this inputs on the device?)
[X] Feedback names of cameras
[X] Feedback of directory row count
[X] Recent call times
[X] Present trigger
[X] Near end camera preset saving
[X] Near end Camera preset select
[X] Presentation start, stop, select discrete
[X] Merge/Join all calls
[X] Incoming call feedback
[X] Incoming call answer/decline
[X] Contact method XSIG

**Items Not Tested**
[ ] Join/Merge/Resume individual call
[ ] DTMF dialing per call
[ ] Speed Dials (Stored in Essentials config)
[ ] Far end Camera preset saving
[ ] Far end Camera preset select
[ ] Far end camera control
[ ] Join meeting trigger
[ ] Update meetings trigger
[ ] Feedback of minutes before meeting start, meeting is joinable, and meeting count
[ ] Schedule data XSIG
[ ] Current layout name
[ ] Current participants XSIG
[ ] Current call direction name
[ ] Advance self-view position name

**Comment by ndorin** [comment]
Update from further testing:

[x] CallXX.Hold.Btn and Fb is not working.
[x] Pressing half-wake does not reflect feedback from codec that it's in half-wake. Requesting half-wake doesn't seem to force device to half-wake. Feedback of half-wake is not reported
The codec isn't reporting feedback for the halfwake state properly.  Setting to halfwake works, but no FB
[x] When attempting to hang up call 1, there is an index out of range exception at: 'VideoCodec.VideoCodecBase+<>c__DisplayClass48.b__3a ()'. I can still trigger the hangUpAllCalls, but I am not able to individually hang up call-1 without receiving the exception.
[x] 'Incoming Call Name' on joinMap ID 51 and 'Incoming Call Number' on joinMap ID 52 are not populating during an incoming call.
[ ] When restarting Essentials while codec in a call, getting a JSON deserialization exception due to unexpected character. It happens often, but seems to change at what position the character is received at.
this will require some more in depth debugging to grab the offending response and find the invalid character.  If it only happens if the program starts while a call is in progress I'm slightly less concerned about this one, but we do need to try to solve it eventually.
[ ] Serial text feedback for "IPv4-Address" not populating
May require further testing, but codec isn't reporting an IPv4 address in it's configuration.  I added code to pull it from Status.Network.IPv4.Address but that doesn't seem to be working currently. This seems to be more of a codec issue than a code issue though.  The IP address should be reported by the codec under Configuration.Network.IPv4.Address and it's not there...

**Comment by jonnyarndt** [comment]
Thanks ND, a lot of progress has been made here. Updates from my testing are below. I've continued updating the 'Not Tested' items for full disclosure.

**##Problems Ongoing**
[ ] Serial text feedback for "IPv4-Address" not populating. [ND: May require further testing, but codec isn't reporting an IPv4 address in it's configuration. I added code to pull it from Status.Network.IPv4.Address but that doesn't seem to be working currently. This seems to be more of a codec issue than a code issue though. The IP address should be reported by the codec under Configuration.Network.IPv4.Address and it's not there...]
[ ] Current call direction not populating (joinMap serial ID 22). Note that the 'Current Call Data - XSIG' on joinMap serial ID 2 does provide the call direction per call.

**Items Tested & Confirmed Working**
[X] Phonebook directory feedback of names
[X] Recent call list feedback of names
[X] Self-View Toggle
[X] Ringtone volume Fb
[X] SIP Phone.Fb and SIP.URI.Fb
[X] Standby state trigger and feedback
[X] DND on/off and feedback state
[X] Camera names propagate
[X] Interesting! Selecting a camera seems to select 'Main' inputs on the VC codec
[X] HangUpAllCalls
[X] Hang-Up Call (1-x)
[X] Recent call select and pressing 'Connect' from Recent Calls
[X] Device Online feedback state
[X] Speaker-Track auto, manual, and off select and feedback
[X] Volume up/down/mute/mute toggle, and manual set as well as feedback
[X] Mic mute on/off/toggle and feedback
[X] Toggle self-view and feedback
[X] Feedback of number of connected calls
[X] Feedback of the number of reported cameras (is this really cameras or is this inputs on the device?)
[X] Feedback names of cameras
[X] Feedback of directory row count
[X] Recent call times
[X] Present trigger
[X] Near end camera preset saving
[X] Near end Camera preset select
[X] Presentation start, stop, select discrete
[X] Merge/Join all calls
[X] Incoming call feedback
[X] Incoming call answer/decline
[X] 'Incoming Call Name' and 'Incoming Call Number' (joinMap ID 51 & 52)
[X] Contact method XSIG
[X] Join/Merge/Resume individual call
[X] Current layout name

**Items Not Tested**
[ ] DTMF dialing per call
[ ] Speed Dials (Stored in Essentials config)
[ ] Far end Camera preset saving
[ ] Far end Camera preset select
[ ] Far end camera control
[ ] Join meeting trigger
[ ] Update meetings trigger
[ ] Feedback of minutes before meeting start, meeting is joinable, and meeting count
[ ] Schedule data XSIG
[ ] Current participants XSIG
[ ] Advance self-view position name
[ ] Half-wake trigger or feedback
