### ISSUE TITLE
[FEATURE]-CreateCommForDevice method should include eControlMethod.Http and return GenericHttpClient 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#880]

**Comment by andrew-welker** [comment]
We need to implement a different interface for this though. HTTP communications is inherently NOT a stream-based communication method, so it doesn't fit into the `IBasicCommunications` method.

**Comment by jtalborough** [comment]
PepperDash.Essentials.Core has a class GenericHttpClient which implements IBasicCommunication. The method CreateCommForDevice returns an IBasicCommunication.

**Comment by ndorin** [comment]
Agreed.

We’ve talked about having a new interface called IRequestResponse or similar and having an override for CreateCommForDevice that returns an instance that implements that interface.

Also I’m not sure that there is a GenericHttpClient class that is feature complete.  Regardless we would not be able to implement IBasicCommunication on such a class, because as Andrew has suggested, Http communication doesn’t match the streaming communication paradigm described by IBasicCommunication.

Thanks,

Neil Dorin
Software Developer /SC
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>


PepperDash Mobile Control<http://www2.pepperdash.com/learn-about-mobile-control>™ - BYOD Crestron Control, no special app required

**Comment by andrew-welker** [comment]
> PepperDash.Essentials.Core has a class GenericHttpClient which implements IBasicCommunication. The method CreateCommForDevice returns an IBasicCommunication.

Yes, it does. Doesn't mean that it's correct or the right way to do this, which is why it hadn't already been implemented into the Comm Factory.
